#!/bin/bash

###############################################
# Setup HOST
###############################################

HOST_NAME=bootc-min
hostnamectl hostname $HOST_NAME

###############################################
# Setup USERS
###############################################

homectl firstboot

###############################################
# Setup FIREWALL
###############################################

if [ "$(firewall-cmd --get-default-zone)" != "public" ]; then firewall-cmd --set-default-zone=public; fi
firewall-cmd --reload
